### ISSUE TITLE
Codex - rust client calling wrong api endpoint

### ISSUE THREAD

**Issue by zeryx** [algorithmiaio/algorithmia-rust#4]
when trying to download a file on a codex installation, I discovered that it was throwing the following exception:
```
couldn't download file from url: data://zeryx/binaries/ffmpeg-static.tar.gz 
401 Unauthorized
```
when talking with @pmcq it was discovered that on the api logs it was reported as:
```
 {"start_date":"2016-11-03T21:22:11.578Z","start_time":1478208131578,"end_time":1478208131581,"method":"GET","uri":"//v1/data/zeryx/bin/ffmpeg-static.tar.gz","status_code":401,"request_time":3,"ip":"156.34.17.89","user_agent":"algorithmia-rust/1.3.0 (Rust unknown","auth_user":"zeryx"}

2016-11-03T21:10:03.987 [application-akka.actor.default-dispatcher-48982] INFO  application : data_v0 GET error, no auth - path: zeryx/binaries/ffmpeg-static.tar.gz error: Authorizat
ionRequired(missing auth) request_headers: ArrayBuffer((User-Agent,algorithmia-rust/1.3.0 (Rust unknown), (Authorization,Simple <snip>), (Host,api.codexonazure.
com))
```
it looks like it's trying to call the data_v0 endpoint which is invalid on codex, breaking the rust client for all codex installations.

**Comment by anowell** [comment]
Accidentally closed? Or did you resolve this somehow?

**Comment by anowell** [comment]
Basically serializing the result of `Url::parse` will end with a `/` (assuming there was no path component). That caused the extra slash to appear (which prevented our API from noticing it as a v1 request, causing it to be mistaken as a v0 request).

This was already fixed in my 2.x overhaul, and will get another round of treatment to use typed Url path joining instead of String joining. The latter would break 1.x compat, so this commit backported the former to 1.x. 

Verify with `algorithmia = { git = "https://github.com/algorithmiaio/algorithmia-rust#1.x" }`. If it works, I'll publish 1.4

**Comment by zeryx** [comment]
I migrated the issue to the main algorithmia repo since it's possibly a multi-client issue and it pertains to codex (which I figured we would want to do) but I'll reopen this instead.

When I attempted to verify with the following addition to the cargo.toml file:

```
[dependencies]
...
#algorithmia = "1.3.0"
algorithmia = { git = "https://github.com/algorithmiaio/algorithmia-rust#1.x" }
...
```

I recieved the following compiler error:

```
    Updating git repository `https://github.com/algorithmiaio/algorithmia-rust#1.x`
warning: spurious network error (2 tries remaining): [12/-1] Unexpected HTTP status code: 400
warning: spurious network error (1 tries remaining): [12/-1] Unexpected HTTP status code: 400
error: failed to load source for a dependency on `algorithmia`

Caused by:
  Unable to update https://github.com/algorithmiaio/algorithmia-rust#1.x

Caused by:
  failed to fetch into /home/james/.cargo/git/db/algorithmia-rust-5f932e6b22887c20
```

**Comment by anowell** [comment]
fixed by using the right syntax

```
algorithmia = { git = "https://github.com/algorithmiaio/algorithmia-rust", branch = "1.x" }
```

I'll get 1.4 published soon
